# Generated by Django 4.2.25 on 2026-01-14 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spending',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='spending',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='spending',
            index=models.Index(fields=['user', 'date'], name='core_spendi_user_id_2e5ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='spending',
            index=models.Index(fields=['category', 'date'], name='core_spendi_categor_c24cd7_idx'),
        ),
    ]
