# Generated by Django 4.2.25 on 2026-01-17 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_spending_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('budget_master', 'Budget Master'), ('savings_champion', 'Savings Champion'), ('thrifty_shopper', 'Thrifty Shopper'), ('goal_crusher', 'Goal Crusher'), ('spending_slayer', 'Spending Slayer'), ('elite_saver', 'Elite Saver'), ('social_saver', 'Social Saver'), ('year_legend', 'Year Legend')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('gradient_start', models.CharField(max_length=10)),
                ('gradient_end', models.CharField(max_length=10)),
                ('target_value', models.IntegerField(default=30)),
                ('category', models.CharField(blank=True, choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('groceries', 'Groceries'), ('transportation', 'Transportation'), ('healthcare', 'Healthcare'), ('savings', 'Savings'), ('other', 'Other')], max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('earned', models.BooleanField(default=False)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='core.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
