# Generated by Django 4.2.25 on 2026-01-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_badge_userbadge'),
        ('core', '0004_chatthread_chatmessage'),
    ]

    operations = [
    ]
