# Generated by Django 4.2.25 on 2026-01-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260117_1152'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='spending',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'date'), name='uniq_spending_user_cat_date'),
        ),
    ]
